In [1]:
class Vector:
    def __init__(self,x=0,y=0):
        self.x=x
        self.y=y
    def __str__(self):
        return "["+str(self.x)+","+str(self.y)+"]"

In [2]:
a=Vector()
print(a)

[0,0]


In [3]:
a=Vector(5,5)

In [4]:
print(a)

[5,5]


In [5]:
def add(self,b):
    c=Vector()
    c.x=self.x + b.x
    c.y=self.y + b.y
    return c
    

In [6]:
Vector.add=add

In [7]:
b=Vector(4,6)
d=a.add(b)
print(d)

[9,11]


In [8]:
def sub(self,b):
    c=Vector()
    c.x=self.x - b.x
    c.y=self.y - b.y
    return c
Vector.sub=sub       

In [9]:
c=a.sub(b)
print(c)

[1,-1]


In [10]:
def mul(self,b):
    c=Vector()
    c.x=self.x * b
    c.y=self.y * b
    return Vector(str(c.x),str(c.y))
Vector.mul=mul

In [11]:
print(a.mul(5))

[25,25]


In [12]:
def dot_product(self,b):
    c.x= self.x * b.y
    c.y= self.y * b.x
    return c.x + c.y
Vector.dot_product=dot_product

In [13]:
d_p=a.dot_product(b)
print(d_p)

50


In [14]:
class Matrix:
    def __init__(self,dim,fill): #Dimension will be Tuple and fill will the element from whose we want to create the list
        self.rows=dim[0]
        self.cols=dim[1]
        self.A=[                 #This is called as list comprehension.
                                 #Square brackets also the part of syntax.
            [fill] * self.cols   #fill * self.cols here results in [2.0 2.0 2.0] (Like the number of columns we indicate here)
            for i in range(self.rows)
        ] 


In [15]:
def __str__(self):
    rows = len(self.A) # here len returns the number of elements it has as I have made a list of list earlier
    ret = ''
    for i in range(rows):
        cols = len(self.A[i]) #here it will move to 1st element(Considering its length there)
        for j in range(cols):
            ret += str(self.A[i][j]) + "\t"
        ret += "\n"
    return ret
Matrix.__str__=__str__

In [16]:
m= Matrix((3,4),2.0)

In [17]:
print(m)

2.0	2.0	2.0	2.0	
2.0	2.0	2.0	2.0	
2.0	2.0	2.0	2.0	



In [18]:
%time n=Matrix((100,100),0.0)

CPU times: total: 0 ns
Wall time: 0 ns


In [19]:
from sys import getsizeof
print(getsizeof(m)) # Why 48 because it is just holding pointer address+ Count(Number of variables attached to it)+
# The type it is of
print(getsizeof(n))

48
48


In [20]:
!pip install pympler    #This is an external package for calculating size.
from pympler.asizeof import asizeof

ERROR: Invalid requirement: '#This': Expected package name at the start of dependency specifier
    #This
    ^


In [21]:
print(asizeof(m)) #Gives result in bytes
print(asizeof(n)) 

760
86896


In [22]:
dim=5000
# %time c=Matrix((dim,dim),0.0)

In [23]:
size= asizeof(c)/(1024*1024) #Kilo=>Mega
print("{:.2f} MB's".format(size))

0.00 MB's


In [24]:
def get(self,i,j):
    if i<0 or i>self.rows:
        print("Rows index out of range")
    if j<0 or j>self.cols:
        print("Cols index out of range")
    return self.A[i][j]
Matrix.get=get

In [25]:
n.get(25,35)

0.0

In [26]:
class Matrix:
    def __init__(self,dim):
        self.rows=dim[0]
        self.cols=dim[1]
        self.vals={}    
    

In [27]:
def set(self,i,j,val):
    if i<0 or i>self.rows:
         print("Rows index out of range")
    if j<0 or j>self.cols:
        print("Cols index out of range")
    self.vals[(i,j)]=val

def get(self,i,j):
    if i<0 or i>self.rows:
         print("Rows index out of range")
    if j<0 or j>self.cols:
        print("Cols index out of range")
    if (i,j) in self.vals:
        return self.vals[(i,j)]
    return 0.0
Matrix.set=set
Matrix.get=get

In [28]:
n=Matrix((dim,dim))
n.set(1,0,2.0)

In [29]:
n.get(1,0)

2.0

In [30]:
n.get(2,5)

0.0

In [31]:
asizeof(n)

720

In [32]:
import numpy as np
np.set_printoptions(suppress=True, precision=2)

x=np.array([1,4,7])
x

array([1, 4, 7])

In [33]:
y=np.array([[1,4,7],[3,5,9]]) # Its now a 2D structure or Matrix
y

array([[1, 4, 7],
       [3, 5, 9]])

In [34]:
x.shape #This is called as rank-1 Tensor

(3,)

In [35]:
y.shape

(2, 3)

In [36]:
z=np.array([[1,4,3]]) # A list having single element in which it has 3 elements
print(z)
z.shape

[[1 4 3]]


(1, 3)

In [37]:
x=np.arange(1,2000,1) #start,end,step
x[:-20]

array([   1,    2,    3, ..., 1977, 1978, 1979])

In [38]:
x.shape

(1999,)

In [39]:
np.arange(0.5, 3, 0.5)

array([0.5, 1. , 1.5, 2. , 2.5])

In [40]:
np.arange(0.5, 10, 1).reshape(5, 2).shape

(5, 2)

In [41]:
np.arange(0.5, 10, 1).reshape(5, 3).shape

ValueError: cannot reshape array of size 10 into shape (5,3)

In [42]:
np.linspace(3, 9, 10)

array([3.  , 3.67, 4.33, 5.  , 5.67, 6.33, 7.  , 7.67, 8.33, 9.  ])

<b>"Basics Of Matrix Operation"<b>

In [43]:
a=np.zeros((3,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [44]:
b=np.ones((3,4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [45]:
c=np.arange(7) # Creates rank-1 tensor
c 

array([0, 1, 2, 3, 4, 5, 6])

In [46]:
c[3]=8 # Taking operation as inplace.
c

array([0, 1, 2, 8, 4, 5, 6])

In [47]:
c[:2]=[17,25]
c

array([17, 25,  2,  8,  4,  5,  6])

In [48]:
c[:2]=[17,25,5]
c

ValueError: could not broadcast input array from shape (3,) into shape (2,)

In [49]:
c[2:2]=[85]
c

array([17, 25,  2,  8,  4,  5,  6])

In [50]:
b[0,0]=5
b[1,2]=14
b[3,2]=78

IndexError: index 3 is out of bounds for axis 0 with size 3

In [51]:
b[0,0]=5 #Assigning at a particular location
b[1,2]=14
b[2,2]=78
b

array([[ 5.,  1.,  1.,  1.],
       [ 1.,  1., 14.,  1.],
       [ 1.,  1., 78.,  1.]])

In [52]:
b.shape


(3, 4)

<h4><b>Array Operations</b></h4>

In [53]:
print(b)

[[ 5.  1.  1.  1.]
 [ 1.  1. 14.  1.]
 [ 1.  1. 78.  1.]]


In [54]:
b + 2 #Assumption it will add 2 at each element.
#Broadcasting Rule: When you add a single number (scalar) to a 2D array, NumPy "stretches"
#that number to match the shape of the matrix and performs the addition element-wise. 

array([[ 7.,  3.,  3.,  3.],
       [ 3.,  3., 16.,  3.],
       [ 3.,  3., 80.,  3.]])

In [55]:
b * 2 # This is performing outplace opertaion.
# As it is creating new copy and making changes in that.

array([[ 10.,   2.,   2.,   2.],
       [  2.,   2.,  28.,   2.],
       [  2.,   2., 156.,   2.]])

In [56]:
b ** 2  # Outplace + Squaring each individual element.

array([[  25.,    1.,    1.,    1.],
       [   1.,    1.,  196.,    1.],
       [   1.,    1., 6084.,    1.]])

In [57]:
sum(b) # Default Sum. Adding column wise.


array([ 7.,  3., 93.,  3.])

In [58]:
b.sum() #Numpy array sum. Just sum the each element of arrat.

106.0

In [59]:
b

array([[ 5.,  1.,  1.,  1.],
       [ 1.,  1., 14.,  1.],
       [ 1.,  1., 78.,  1.]])

In [60]:
b.sum(axis=0).shape # Column wise

(4,)

In [61]:
b.sum(axis=1).shape #Row wise

(3,)

In [62]:
d= np.array(([1,2],[3,5]))
e= np.array(([1,1],[2,6]))


In [63]:
print(d)
print(e)
d + e # Added every element to element.

[[1 2]
 [3 5]]
[[1 1]
 [2 6]]


array([[ 2,  3],
       [ 5, 11]])

In [64]:
print(d)
print(e) 
d * e # Multiplying every element.

[[1 2]
 [3 5]]
[[1 1]
 [2 6]]


array([[ 1,  2],
       [ 6, 30]])

In [65]:
d.dot(e) # Now performs actuall matrix multiplication.

array([[ 5, 13],
       [13, 33]])

In [66]:
print(d)
print(e) 
d ** e # 1 power 1 , 2 power 1 , ... , 6 power 5

[[1 2]
 [3 5]]
[[1 1]
 [2 6]]


array([[    1,     2],
       [    9, 15625]])

In [67]:
d.T # Taken tranpose.

array([[1, 3],
       [2, 5]])

In [68]:
d.T.shape

(2, 2)

In [69]:
d.reshape(1,4).T

array([[1],
       [2],
       [3],
       [5]])

In [70]:
# Checking conditions 
x = np.array([1, 2, 4, 5, 9, 3])
y = np.array([0, 2, 3, 1, 2, 3])

In [71]:
x > y # Compares every single element.

array([ True, False,  True,  True,  True, False])

In [72]:
import math
def basic_sigmoid(x): #This is writing sigmoid function which gives 0 at -infinity and 1 at +ve infinity.
    """
    Compute sigmoid of x. 

    Arguments:
    x -- A scalar

    Return:
    s -- sigmoid(x)
    """
    
    s = 1./(1. + math.e ** (-x))
    
    return s

In [73]:
x=math.sqrt(25)
x

5.0

In [74]:
basic_sigmoid(x)

0.9933071490757153

In [75]:
 z=[2,4,5,3] # It doesnot work because functions are defined to be work on scalar. Not lists
basic_sigmoid(z) 

TypeError: bad operand type for unary -: 'list'

In [76]:
import numpy as np

x = [-1, 0, 3]
x = np.array(x) #Now it works because array somehow able to perform on single operation because 
# Numpy is written like this somehow.

basic_sigmoid(x)

array([0.27, 0.5 , 0.95])

<h3><b>"Broad Casting"</b></h3>

In [1]:
import numpy as np

In [3]:
x=np.array([1,2,3])
x * 3

array([3, 6, 9])

In [4]:
x + 3

array([4, 5, 6])

In [5]:
x.shape

(3,)

<b>Generl rule: Two dimensions are compatible when

they are equal, or

one of them is 1</b>

In [6]:
x = np.arange(4)
xx = x.reshape(4, 1)
y = np.ones(5)
z = np.ones((3,4))

print("x =  ", x)
print("xx = ", xx) 
print("y =  ", y)

print("Shapes: ") 
print(x.shape)
print(xx.shape)
print(y.shape)


x =   [0 1 2 3]
xx =  [[0]
 [1]
 [2]
 [3]]
y =   [1. 1. 1. 1. 1.]
Shapes: 
(4,)
(4, 1)
(5,)


In [7]:
xx + y #BroadCasting xx onto y 

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])