In [1]:
class Vector:
    def __init__(self,x=0,y=0):
        self.x=x
        self.y=y
    def __str__(self):
        return "["+str(self.x)+","+str(self.y)+"]"

In [2]:
a=Vector()
print(a)

[0,0]


In [3]:
a=Vector(5,5)

In [4]:
print(a)

[5,5]


In [5]:
def add(self,b):
    c=Vector()
    c.x=self.x + b.x
    c.y=self.y + b.y
    return c
    

In [6]:
Vector.add=add

In [7]:
b=Vector(4,6)
d=a.add(b)
print(d)

[9,11]


In [8]:
def sub(self,b):
    c=Vector()
    c.x=self.x - b.x
    c.y=self.y - b.y
    return c
Vector.sub=sub       

In [9]:
c=a.sub(b)
print(c)

[1,-1]


In [10]:
def mul(self,b):
    c=Vector()
    c.x=self.x * b
    c.y=self.y * b
    return Vector(str(c.x),str(c.y))
Vector.mul=mul

In [11]:
print(a.mul(5))

[25,25]


In [12]:
def dot_product(self,b):
    c.x= self.x * b.y
    c.y= self.y * b.x
    return c.x + c.y
Vector.dot_product=dot_product

In [13]:
d_p=a.dot_product(b)
print(d_p)

50


In [14]:
class Matrix:
    def __init__(self,dim,fill): #Dimension will be Tuple and fill will the element from whose we want to create the list
        self.rows=dim[0]
        self.cols=dim[1]
        self.A=[                 #This is called as list comprehension.
                                 #Square brackets also the part of syntax.
            [fill] * self.cols   #fill * self.cols here results in [2.0 2.0 2.0] (Like the number of columns we indicate here)
            for i in range(self.rows)
        ] 


In [15]:
def __str__(self):
    rows = len(self.A) # here len returns the number of elements it has as I have made a list of list earlier
    ret = ''
    for i in range(rows):
        cols = len(self.A[i]) #here it will move to 1st element(Considering its length there)
        for j in range(cols):
            ret += str(self.A[i][j]) + "\t"
        ret += "\n"
    return ret
Matrix.__str__=__str__

In [22]:
m= Matrix((3,4),2.0)

3


In [23]:
print(m)

2.0	2.0	2.0	2.0	
2.0	2.0	2.0	2.0	
2.0	2.0	2.0	2.0	



In [47]:
%time n=Matrix((100,100),0.0)

100
CPU times: total: 0 ns
Wall time: 5.36 ms


In [41]:
from sys import getsizeof
print(getsizeof(m)) # Why 48 because it is just holding pointer address+ Count(Number of variables attached to it)+
# The type it is of
print(getsizeof(n))

48
48


In [43]:
!pip install pympler    #This is an external package for calculating size.
from pympler.asizeof import asizeof

ERROR: Invalid requirement: '#This': Expected package name at the start of dependency specifier
    #This
    ^


In [48]:
print(asizeof(m)) #Gives result in bytes
print(asizeof(n)) 

760
86896


In [115]:
dim=5000
# %time c=Matrix((dim,dim),0.0)

In [50]:
size= asizeof(c)/(1024*1024) #Kilo=>Mega
print("{:.2f} MB's".format(size))

191.04MB's


In [58]:
def get(self,i,j):
    if i<0 or i>self.rows:
        print("Rows index out of range")
    if j<0 or j>self.cols:
        print("Cols index out of range")
    return self.A[i][j]
Matrix.get=get

In [65]:
n.get(25,35)

0.0

In [67]:
class Matrix:
    def __init__(self,dim):
        self.rows=dim[0]
        self.cols=dim[1]
        self.vals={}    
    

In [102]:
def set(self,i,j,val):
    if i<0 or i>self.rows:
         print("Rows index out of range")
    if j<0 or j>self.cols:
        print("Cols index out of range")
    self.vals[(i,j)]=val

def get(self,i,j):
    if i<0 or i>self.rows:
         print("Rows index out of range")
    if j<0 or j>self.cols:
        print("Cols index out of range")
    if (i,j) in self.vals:
        return self.vals[(i,j)]
    return 0.0
Matrix.set=set
Matrix.get=get

In [107]:
n=Matrix((dim,dim))
n.set(1,0,2.0)

In [108]:
n.get(1,0)

2.0

In [105]:
n.get(2,5)

0.0

In [116]:
asizeof(n)

720

In [119]:
import numpy as np
x=np.array([1,4,7])
x

array([1, 4, 7])

In [123]:
y=np.array([[1,4,7],[3,5,9]]) # Its now a 2D structure or Matrix
y

array([[1, 4, 7],
       [3, 5, 9]])

In [131]:
x.shape #This is called as rank-1 Tensor

(3,)

In [126]:
y.shape

(2, 3)

In [130]:
z=np.array([[1,4,3]]) # A list having single element in which it has 3 elements
print(z)
z.shape

[[1 4 3]]


(1, 3)

In [140]:
x=np.arange(1,2000,1) #start,end,step
x[:-20]

array([   1,    2,    3, ..., 1977, 1978, 1979])

In [139]:
x.shape

(1999,)

In [141]:
np.arange(0.5, 3, 0.5)

array([0.5, 1. , 1.5, 2. , 2.5])

In [144]:
np.arange(0.5, 10, 1).reshape(5, 2).shape

(5, 2)

In [145]:
np.arange(0.5, 10, 1).reshape(5, 3).shape

ValueError: cannot reshape array of size 10 into shape (5,3)

In [146]:
np.linspace(3, 9, 10)

array([3.        , 3.66666667, 4.33333333, 5.        , 5.66666667,
       6.33333333, 7.        , 7.66666667, 8.33333333, 9.        ])